pretrained_model_artifact_name: "pretrain_gadgil2023_cube_split_1"

batch_size: 128
lr: 0.001
hard_budget: 20
nepochs: 250
patience: 5
eps: 0.05
eps_decay: 0.2
eps_steps: 10

hidden_units: [128,128]
dropout: 0.3
activations: 'ReLU'
flag_drop_out: True
flag_only_output_layer: False
