dataset_artifact_name: "miniboone_split_1:tmp"
batch_size: 128 # shim2018 paper
epochs: 200
limit_train_batches: null
limit_val_batches: null

lr: 1e-3
min_masking_probability: 0.0
max_masking_probability: 0.9
pq_module:
  n_hiddens: [64,32,16] # kachuee2019 implementation for Diabetes
  p_dropout: 0.5 # kachuee2019 implementation
